name: resolver
version: 0.1.1
author: Matan Lurey <matan@lurey.org>
description: Simple frontend for resolving Dart code
homepage: https://github.com/matanlurey/resolver

environment:
  sdk: '>=1.21.0 <2.0.0'

dependencies:
  analyzer: '^0.29.2'

dev_dependencies:
  path: '^1.0.0'
  test: '^0.12.17'
